server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://42.194.178.20:5432/final
    username: final
    password: CS307final
  thymeleaf:
    cache: false
#  mvc:
#    static-path-pattern: /res/**
debug: true
